VERBOSE_LOGS: false
TRIM_METADATA: false
PROXY: "http://127.0.0.1:7897"
PREFERRED_LANGUAGE: en
PREFERRED_AUDIO_CODEC: aac
PREFERRED_VIDEO_CODEC: vp9
PREFERRED_VIDEO_EXT: mp4
EMBED_SUBS: false
WRITE_SUBS: false
ALLOW_AUTO_SUBS: true
SUBTITLE_FORMAT: vtt
SUBTITLE_LANGUAGES: en
THREAD_COUNT: 4
