VERBOSE_LOGS: false
TRIM_METADATA: false
JS_RUNTIMES: "node"
PREFERRED_LANGUAGE: zh-Hant
PREFERRED_AUDIO_CODEC: aac
PREFERRED_VIDEO_CODEC: vp9
PREFERRED_VIDEO_EXT: mp4
EMBED_SUBS: false
WRITE_SUBS: true
ALLOW_AUTO_SUBS: true
SUBTITLE_FORMAT: vtt
SUBTITLE_LANGUAGES: zh-Hant
THREAD_COUNT: 4
