General:
  audio_ext: m4a
  audio_format_id: '140'
  video_ext: mp4
  video_format_id: '303'
Music:
  audio_ext: mp3
  audio_format_id: '140'
Podcast:
  audio_ext: m4a
  audio_format_id: '140'
Video:
  audio_format_id: '140'
  video_ext: mp4
  video_format_id: 'bestvideo[height<=720][ext=mp4]'
